
world keyvalue {
	import readwrite: pkg.wasi-keyvalue.keyvalue-readwrite
	import atomic: pkg.wasi-keyvalue.keyvalue-atomic
	import batch: pkg.wasi-keyvalue.keyvalue-batch
}

world keyvalue-handle-watch {
	import readwrite: pkg.wasi-keyvalue.keyvalue-readwrite
	import atomic: pkg.wasi-keyvalue.keyvalue-atomic
	import batch: pkg.wasi-keyvalue.keyvalue-batch
	export handle-watch: pkg.wasi-keyvalue.handle-watch
}
